// Cognito Configuration - Generated by setup script
const cognitoConfig = {
    UserPoolId: 'eu-west-1_WtPApI9cc',
    ClientId: '5niqc7g1ugll4qsl4fni28kfbl',
    Region: 'eu-west-1',
    Domain: 'translation-app-dev.auth.eu-west-1.amazoncognito.com',
    ApiGatewayUrl: "https://q9donrblw2.execute-api.eu-west-1.amazonaws.com/prod/upload",
    OriginalFileUrl: "https://q9donrblw2.execute-api.eu-west-1.amazonaws.com/prod/files",
    PresignedUrlEndpoint: "endpoint-for-presigned-urls",
    ListFilesEndpoint: "https://q9donrblw2.execute-api.eu-west-1.amazonaws.com/prod/files",
    UserFilesEndpoint: "https://q9donrblw2.execute-api.eu-west-1.amazonaws.com/prod/get_user_uploads",



};

// Copy these values to your app configuration
console.log('AWS Cognito Configuration:');
console.log('UserPoolId:', cognitoConfig.UserPoolId);
console.log('ClientId:', cognitoConfig.ClientId);
console.log('Region:', cognitoConfig.Region);
console.log('Domain:', cognitoConfig.Domain);