// // Cognito Configuration - Generated by setup script
// const cognitoConfig = {
//     UserPoolId: 'eu-west-1_xtU01rXnA',
//     ClientId: '4br4u9oa2c3goujddbhk2g31gq',
//     Region: 'eu-west-1',
//     Domain: 'translation-app-dev.auth.eu-west-1.amazoncognito.com',
//     ApiGatewayUrl: "https://pw5o84s8qi.execute-api.eu-west-1.amazonaws.com/prod/upload",
//     OriginalFileUrl: "https://pw5o84s8qi.execute-api.eu-west-1.amazonaws.com/prod/files",
//     PresignedUrlEndpoint: "endpoint-for-presigned-urls",
//     ListFilesEndpoint: "https://pw5o84s8qi.execute-api.eu-west-1.amazonaws.com/prod/files",
//     UserFilesEndpoint: "https://pw5o84s8qi.execute-api.eu-west-1.amazonaws.com/prod/get_user_uploads",
//     OutputBucketUrl: "https://translation-app-output-bucket-cffe65b78aa6b938.s3.eu-west-1.amazonaws.com",
//     apiKeyUrl: ""



// };



// Cognito Configuration - Loaded from environment variables
const cognitoConfig = {
    UserPoolId: process.env.COGNITO_USER_POOL_ID,
    ClientId: process.env.COGNITO_CLIENT_ID,
    Region: process.env.COGNITO_REGION,
    Domain: process.env.COGNITO_DOMAIN,
    ApiGatewayUrl: process.env.API_GATEWAY_URL,
    OriginalFileUrl: process.env.ORIGINAL_FILE_URL,
    PresignedUrlEndpoint: process.env.PRESIGNED_URL_ENDPOINT,
    ListFilesEndpoint: process.env.LIST_FILES_ENDPOINT,
    UserFilesEndpoint: process.env.USER_FILES_ENDPOINT,
    OutputBucketUrl: process.env.OUTPUT_BUCKET_URL,
    apiKeyUrl: process.env.API_KEY_URL
};

// Optional: Add validation to ensure required variables are set
if (!cognitoConfig.UserPoolId || !cognitoConfig.ClientId) {
    console.error("Missing required Cognito configuration");
    // Handle error appropriately for your application
}